# **IMPORT NECESSARY LIBRARIES**

In [ ]:
import pickle
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# **LOAD MODELS AND VECTORIZERS**

In [ ]:
try:
    with open('Model_A.pkl', 'rb') as f:
        model_A = pickle.load(f)
    print("Model_A (Trained on Balanced Data) loaded successfully.")

    with open('Model_B.pkl', 'rb') as f:
        model_B = pickle.load(f)
    print("Model_B (Trained on Imbalanced Data) loaded successfully.")

    with open('balanced_tfidf_vectorizer.pkl', 'rb') as f:
        vectorizer_balanced = pickle.load(f)
    print("Balanced TF-IDF Vectorizer loaded successfully.")

    with open('imbalanced_tfidf_vectorizer.pkl', 'rb') as f:
        vectorizer_imbalanced = pickle.load(f)
    print("Imbalanced TF-IDF Vectorizer loaded successfully.")

except FileNotFoundError as e:
    print(f"Error: {e}. Please ensure you have uploaded all four files to your Colab session.")

Model_A (Trained on Balanced Data) loaded successfully.
Model_B (Trained on Imbalanced Data) loaded successfully.
Balanced TF-IDF Vectorizer loaded successfully.
Imbalanced TF-IDF Vectorizer loaded successfully.


# **LOAD TEST DATA**

In [ ]:
imbalanced_df = pd.read_csv('imbalanced_test_final.csv')
balanced_df = pd.read_csv('balanced_test_final.csv')

In [ ]:
# Split into features and labels
X_test_imbal = imbalanced_df['Review']
y_test_imbal = imbalanced_df['Rating']

X_test_bal = balanced_df['Review']
y_test_bal = balanced_df['Rating']

# **EVALUATION FUNCTION**

In [ ]:
# Transform text data using respective vectorizers
X_test_bal_vect = vectorizer_balanced.transform(X_test_bal)
X_test_imbal_vect = vectorizer_imbalanced.transform(X_test_imbal)

In [ ]:
# Make predictions
y_pred_a_bal = model_A.predict(X_test_bal_vect)
y_pred_b_imbal = model_B.predict(X_test_imbal_vect)

In [ ]:
# Transform text data using respective vectorizers
X_test_bal_vect_a = vectorizer_balanced.transform(X_test_bal)
X_test_imbal_vect_b = vectorizer_imbalanced.transform(X_test_imbal)

In [ ]:
# Cross-transform for testing on opposite datasets
X_test_bal_vect_b = vectorizer_imbalanced.transform(X_test_bal)
X_test_imbal_vect_a = vectorizer_balanced.transform(X_test_imbal)

In [ ]:
# Make predictions (Cross-testing and Control-testing)
y_pred_a_imbal = model_A.predict(X_test_imbal_vect_a) # Model A on Imbalanced Test Set
y_pred_b_bal = model_B.predict(X_test_bal_vect_b)   # Model B on Balanced Test Set

# **CROSS TESTING**

In [ ]:
# Evaluate Models

def evaluate_model(y_true, y_pred, model_name):
    print(f"===== Evaluation for {model_name} =====")
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("\nClassification Report:\n", classification_report(y_true, y_pred, digits=4))
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
    print("\n--------------------------------------\n")

# Cross Tests
evaluate_model(y_test_imbal, y_pred_a_imbal, "Model_A on Imbalanced Test Set")
evaluate_model(y_test_bal, y_pred_b_bal, "Model_B on Balanced Test Set")

# Control Tests
evaluate_model(y_test_bal, y_pred_a_bal, "Model_A on Balanced Test Set")
evaluate_model(y_test_imbal, y_pred_b_imbal, "Model_B on Imbalanced Test Set")

===== Evaluation for Model_A on Imbalanced Test Set =====
Accuracy: 0.7913043478260869

Classification Report:
               precision    recall  f1-score   support

           1     0.7854    0.8818    0.8308       220
           2     0.8153    0.7711    0.7926       332
           3     0.7706    0.7802    0.7754       323
           4     0.7802    0.8124    0.7960       437
           5     0.8063    0.7458    0.7748       413

    accuracy                         0.7913      1725
   macro avg     0.7916    0.7982    0.7939      1725
weighted avg     0.7921    0.7913    0.7908      1725

Confusion Matrix:
 [[194  12   8   1   5]
 [ 39 256  26   6   5]
 [  8  25 252  21  17]
 [  2   9  24 355  47]
 [  4  12  17  72 308]]

--------------------------------------

===== Evaluation for Model_B on Balanced Test Set =====
Accuracy: 0.5686666666666667

Classification Report:
               precision    recall  f1-score   support

           1     0.7664    0.5250    0.6231       600
    